import { useState, useEffect } from 'react';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { Plus, Loader2 } from 'lucide-react';

interface Professor {
  user_id: string;
  name: string;
  email: string;
}

interface AddClassDialogProps {
  onSuccess: () => void;
}

export function AddClassDialog({ onSuccess }: AddClassDialogProps) {
  const [open, setOpen] = useState(false);
  const [isLoading, setIsLoading] = useState(false);
  const [professors, setProfessors] = useState<Professor[]>([]);
  const [formData, setFormData] = useState({
    subject: '',
    code: '',
    department: '',
    semester: '',
    room: '',
    professor_id: '',
  });
  const { toast } = useToast();

  useEffect(() => {
    if (open) {
      fetchProfessors();
    }
  }, [open]);

  const fetchProfessors = async () => {
    try {
      const { data: roleData } = await supabase
        .from('user_roles')
        .select('user_id')
        .eq('role', 'professor');

      if (roleData && roleData.length > 0) {
        const professorIds = roleData.map(r => r.user_id);
        const { data: profilesData } = await supabase
          .from('profiles')
          .select('user_id, name, email')
          .in('user_id', professorIds);
        
        setProfessors(profilesData || []);
      }
    } catch (error) {
      console.error('Error fetching professors:', error);
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setIsLoading(true);

    try {
      // Generate join_code - the database trigger will handle this
      const { error } = await supabase
        .from('classes')
        .insert({
          subject: formData.subject,
          code: formData.code,
          department: formData.department,
          semester: formData.semester,
          room: formData.room,
          professor_id: formData.professor_id,
          join_code: '', // Will be generated by trigger
        });

      if (error) throw error;

      toast({ title: 'Success', description: 'Class created successfully' });
      setOpen(false);
      setFormData({ subject: '', code: '', department: '', semester: '', room: '', professor_id: '' });
      onSuccess();
    } catch (error: any) {
      console.error('Error creating class:', error);
      toast({ title: 'Error', description: error.message, variant: 'destructive' });
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <Dialog open={open} onOpenChange={setOpen}>
      <DialogTrigger asChild>
        <Button>
          <Plus className="h-4 w-4 mr-2" />
          Add Class
        </Button>
      </DialogTrigger>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Add New Class</DialogTitle>
        </DialogHeader>
        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="subject">Subject Name *</Label>
            <Input
              id="subject"
              value={formData.subject}
              onChange={(e) => setFormData({ ...formData, subject: e.target.value })}
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="code">Course Code *</Label>
            <Input
              id="code"
              value={formData.code}
              onChange={(e) => setFormData({ ...formData, code: e.target.value })}
              required
            />
          </div>
          <div className="space-y-2">
            <Label htmlFor="professor">Professor *</Label>
            <Select
              value={formData.professor_id}
              onValueChange={(value) => setFormData({ ...formData, professor_id: value })}
            >
              <SelectTrigger>
                <SelectValue placeholder="Select professor" />
              </SelectTrigger>
              <SelectContent>
                {professors.map((prof) => (
                  <SelectItem key={prof.user_id} value={prof.user_id}>
                    {prof.name} ({prof.email})
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="grid grid-cols-2 gap-4">
            <div className="space-y-2">
              <Label htmlFor="department">Department *</Label>
              <Input
                id="department"
                value={formData.department}
                onChange={(e) => setFormData({ ...formData, department: e.target.value })}
                required
              />
            </div>
            <div className="space-y-2">
              <Label htmlFor="semester">Semester *</Label>
              <Input
                id="semester"
                value={formData.semester}
                onChange={(e) => setFormData({ ...formData, semester: e.target.value })}
                required
              />
            </div>
          </div>
          <div className="space-y-2">
            <Label htmlFor="room">Room *</Label>
            <Input
              id="room"
              value={formData.room}
              onChange={(e) => setFormData({ ...formData, room: e.target.value })}
              required
            />
          </div>
          <div className="flex justify-end gap-3">
            <Button type="button" variant="outline" onClick={() => setOpen(false)}>
              Cancel
            </Button>
            <Button type="submit" disabled={isLoading || !formData.professor_id}>
              {isLoading && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              Create Class
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
}
